FROM tensorflow/tensorflow:2.6.1-gpu-jupyter

ENV RUNTIME_PACKAGES="ffmpeg"
ENV BUILD_PACKAGES="build-essential git"

RUN apt-get update -y && \
    apt-get install -y $BUILD_PACKAGES $RUNTIME_PACKAGES && \
    apt-get autoremove -y

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt

ADD . /app

