FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

ENV RUNTIME_PACKAGES="ffmpeg gosu"
    ENV BUILD_PACKAGES="build-essential git"

RUN apt-get update && \
    apt-get install -y libasound2

RUN apt-get update && \
    apt-get install -y $BUILD_PACKAGES $RUNTIME_PACKAGES && \
    apt-get autoremove -y

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt

ADD . /app
WORKDIR /code

ENTRYPOINT ["/app/utils/entrypoint.sh"]
CMD ["jupyter", "lab"]
