apiVersion: v1
kind: Secret
metadata:
    name: {{ include "autotrim.fullname" . }}-secret
type: "Opaque"
stringData:
    # DB credentials
    DB_HOST: {{ .Values.autotrim.postgresHost }}
    DB_PASS: {{ .Values.autotrim.postgresPass }}
    DB_USER: {{ .Values.autotrim.postgresUsername }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.autotrim.aws_secret_access_key }}
    AWS_ACCESS_KEY_ID: {{ .Values.autotrim.aws_access_key_id }}
    AUTOTRIM_STORAGE_BUCKET_PREFIX: {{ .Values.autotrim.storage_bucket_prefix }}
    AUTOTRIM_STORAGE_ENDPOINT_URL: {{ .Values.autotrim.storage_endpoint_url }}
    AUTOTRIM_SOURCE_DIR: {{ .Values.autotrim.source_dir }}